"""
OCR Engine — Multi-backend local text extraction for P&ID drawings.

Priority chain:
  0. PyMuPDF text layer on original PDF (instant, 100% accurate for vector PDFs — try FIRST)
  1. EasyOCR (PyTorch-based, works reliably on Windows — preferred for rasterized)
  2. PaddleOCR v2.x API (if available and working)
  3. PyMuPDF text layer on rasterized image (fallback)

Zero API tokens consumed by any of these methods.
"""
import logging
import os
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)

# Singleton caches
_easyocr_reader = None
_paddleocr_instance = None


def run_pdf_text_extraction(pdf_path: str) -> List[Dict[str, Any]]:
    """
    Extract text directly from a PDF's vector text layer using PyMuPDF.
    This works perfectly for PDFs generated by AutoCAD, AVEVA, SmartPlant, etc.
    Returns immediately for scanned PDFs (no embedded text) with an empty list.

    Each item: text, confidence=0.99, bbox, center_x, center_y (normalized)
    """
    if not os.path.exists(pdf_path) or not pdf_path.lower().endswith('.pdf'):
        return []

    try:
        import pymupdf as fitz
        doc = fitz.open(pdf_path)
        items = []
        for page_idx in range(len(doc)):
            page = doc.load_page(page_idx)
            page_w = page.rect.width or 1
            page_h = page.rect.height or 1
            # Extract individual words with positions
            words = page.get_text("words")  # returns list of (x0,y0,x1,y1,word,block,line,word_idx)
            for block in words:
                x0, y0, x1, y1, word = block[0], block[1], block[2], block[3], block[4]
                word = word.strip()
                if not word or len(word) < 2:
                    continue
                cx = round((x0 + x1) / 2 / page_w, 4)
                cy = round((y0 + y1) / 2 / page_h, 4)
                items.append({
                    "text": word,
                    "confidence": 0.99,
                    "bbox": [[x0, y0], [x1, y0], [x1, y1], [x0, y1]],
                    "center_x": cx,
                    "center_y": cy,
                })
        doc.close()
        if items:
            logger.info(f"PyMuPDF text layer extracted {len(items)} words from '{pdf_path}'.")
        else:
            logger.info(f"PyMuPDF text layer: no embedded text found (likely a scanned PDF).")
        return items
    except Exception as e:
        logger.warning(f"PyMuPDF text layer extraction failed on PDF: {e}")
        return []



# ──────────────────────────────────────────────────────────────────────────────
# EasyOCR Backend (Primary — most reliable on Windows)
# ──────────────────────────────────────────────────────────────────────────────

def _get_easyocr():
    """Lazy-load EasyOCR reader with English model."""
    global _easyocr_reader
    if _easyocr_reader is None:
        import easyocr
        logger.info("Initializing EasyOCR reader (en)...")
        _easyocr_reader = easyocr.Reader(['en'], gpu=False, verbose=False)
        logger.info("EasyOCR initialized successfully.")
    return _easyocr_reader


def _run_easyocr(image_path: str, img_w: int, img_h: int) -> List[Dict[str, Any]]:
    """Run EasyOCR and normalize output to standard item format."""
    reader = _get_easyocr()
    # EasyOCR returns: list of (bbox, text, confidence)
    # bbox = [[x1,y1],[x2,y1],[x2,y2],[x1,y2]]
    raw = reader.readtext(image_path, detail=1, paragraph=False,
                          min_size=5, text_threshold=0.4, low_text=0.25,
                          decoder='greedy', workers=0)
    items = []
    for (bbox, text, conf) in raw:
        if not text.strip() or conf < 0.15:
            continue
        xs = [pt[0] for pt in bbox]
        ys = [pt[1] for pt in bbox]
        center_x = round((sum(xs) / len(xs)) / max(img_w, 1), 4)
        center_y = round((sum(ys) / len(ys)) / max(img_h, 1), 4)
        items.append({
            "text": text.strip(),
            "confidence": round(float(conf), 3),
            "bbox": bbox,
            "center_x": center_x,
            "center_y": center_y,
        })
    return items


# ──────────────────────────────────────────────────────────────────────────────
# PaddleOCR Backend (Secondary — v2.x API only)
# ──────────────────────────────────────────────────────────────────────────────

def _get_paddleocr_v2():
    """Lazy-load PaddleOCR v2.x instance (old API with use_angle_cls etc.)"""
    global _paddleocr_instance
    if _paddleocr_instance is None:
        from paddleocr import PaddleOCR
        import inspect
        sig = inspect.signature(PaddleOCR.__init__)
        params = list(sig.parameters.keys())

        if 'use_angle_cls' in params:
            # v2.x API
            logger.info("Initializing PaddleOCR v2.x engine...")
            _paddleocr_instance = PaddleOCR(
                use_angle_cls=True, lang='en', use_gpu=False,
                show_log=False, det_db_thresh=0.3, det_db_box_thresh=0.4,
                rec_batch_num=6,
            )
            logger.info("PaddleOCR v2.x initialized.")
        else:
            # v3.x — only init without problematic args
            logger.warning("PaddleOCR v3.x detected. Will attempt predict() call.")
            _paddleocr_instance = PaddleOCR(
                lang='en',
                use_doc_orientation_classify=False,
                use_doc_unwarping=False,
                use_textline_orientation=False,
                text_det_thresh=0.3,
                text_det_box_thresh=0.4,
                text_rec_score_thresh=0.2,
            )
    return _paddleocr_instance


def _run_paddleocr(image_path: str, img_w: int, img_h: int) -> List[Dict[str, Any]]:
    """Run PaddleOCR and normalize output."""
    ocr = _get_paddleocr_v2()
    items = []

    # Try v2 .ocr() style first
    try:
        raw = ocr.ocr(image_path, cls=True)
        if raw and raw[0]:
            for line in raw[0]:
                if line is None:
                    continue
                bbox_pts, (text, conf) = line[0], line[1]
                if not text.strip() or conf < 0.2:
                    continue
                xs = [pt[0] for pt in bbox_pts]
                ys = [pt[1] for pt in bbox_pts]
                center_x = round((sum(xs) / len(xs)) / max(img_w, 1), 4)
                center_y = round((sum(ys) / len(ys)) / max(img_h, 1), 4)
                items.append({
                    "text": text.strip(),
                    "confidence": round(float(conf), 3),
                    "bbox": bbox_pts,
                    "center_x": center_x,
                    "center_y": center_y,
                })
        return items
    except Exception:
        pass

    # Try v3 .predict() style
    try:
        raw = ocr.predict(image_path)
        for result in (raw or []):
            if result is None:
                continue
            texts = getattr(result, 'rec_texts', None) or result.get('rec_texts', [])
            scores = getattr(result, 'rec_scores', None) or result.get('rec_scores', [])
            polys = getattr(result, 'dt_polys', None) or result.get('dt_polys', [])
            for text, score, poly in zip(texts, scores, polys):
                if not text.strip() or score < 0.15:
                    continue
                pts = poly.tolist() if hasattr(poly, 'tolist') else list(poly)
                xs = [p[0] for p in pts]
                ys = [p[1] for p in pts]
                center_x = round((sum(xs) / len(xs)) / max(img_w, 1), 4)
                center_y = round((sum(ys) / len(ys)) / max(img_h, 1), 4)
                items.append({
                    "text": text.strip(),
                    "confidence": round(float(score), 3),
                    "bbox": pts,
                    "center_x": center_x,
                    "center_y": center_y,
                })
        return items
    except Exception as e:
        raise RuntimeError(f"PaddleOCR v3 predict() failed: {e}")


# ──────────────────────────────────────────────────────────────────────────────
# PyMuPDF text layer (for PDFs/images with embedded selectable text)
# ──────────────────────────────────────────────────────────────────────────────

def _run_pymupdf_text(image_path: str, img_w: int, img_h: int) -> List[Dict[str, Any]]:
    """Extract text from an image file via PyMuPDF OCR (only works if text layer present)."""
    import pymupdf as fitz
    doc = fitz.open(image_path)
    items = []
    for page in doc:
        blocks = page.get_text("words")
        page_w = page.rect.width or 1
        page_h = page.rect.height or 1
        for block in blocks:
            x0, y0, x1, y1, word, *_ = block
            if not word.strip():
                continue
            cx = round((x0 + x1) / 2 / page_w, 4)
            cy = round((y0 + y1) / 2 / page_h, 4)
            items.append({
                "text": word.strip(),
                "confidence": 0.95,
                "bbox": [[x0, y0], [x1, y0], [x1, y1], [x0, y1]],
                "center_x": cx,
                "center_y": cy,
            })
    doc.close()
    return items


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def run_paddle_ocr(image_path: str) -> List[Dict[str, Any]]:
    """
    Run OCR on an image using the best available local engine.
    Falls through: EasyOCR → PaddleOCR → PyMuPDF text layer.

    Returns list of dicts with: text, confidence, bbox, center_x, center_y.
    """
    if not os.path.exists(image_path):
        logger.error(f"Image not found: '{image_path}'")
        return []

    # Get image dimensions for normalization
    img_w, img_h = 1, 1
    try:
        import cv2
        img = cv2.imread(image_path)
        if img is not None:
            img_h, img_w = img.shape[:2]
    except Exception:
        try:
            from PIL import Image as PILImage
            pil = PILImage.open(image_path)
            img_w, img_h = pil.size
        except Exception:
            pass

    # ── Try EasyOCR first ─────────────────────────────────────────────────────
    try:
        logger.info(f"Running EasyOCR on '{image_path}'...")
        items = _run_easyocr(image_path, img_w, img_h)
        if items:
            logger.info(f"EasyOCR extracted {len(items)} text items.")
            return items
        else:
            logger.warning("EasyOCR returned 0 items. Trying PaddleOCR fallback.")
    except Exception as e:
        logger.warning(f"EasyOCR failed ({e}). Trying PaddleOCR.")

    # ── Try PaddleOCR ─────────────────────────────────────────────────────────
    try:
        logger.info(f"Running PaddleOCR on '{image_path}'...")
        items = _run_paddleocr(image_path, img_w, img_h)
        if items:
            logger.info(f"PaddleOCR extracted {len(items)} text items.")
            return items
        else:
            logger.warning("PaddleOCR returned 0 items. Trying PyMuPDF text layer.")
    except Exception as e:
        logger.warning(f"PaddleOCR failed ({e}). Trying PyMuPDF text layer.")

    # ── Try PyMuPDF text extraction ───────────────────────────────────────────
    try:
        logger.info(f"Trying PyMuPDF text layer extraction on '{image_path}'...")
        items = _run_pymupdf_text(image_path, img_w, img_h)
        if items:
            logger.info(f"PyMuPDF extracted {len(items)} text items.")
            return items
    except Exception as e:
        logger.warning(f"PyMuPDF text extraction failed ({e}).")

    logger.error(f"All OCR backends failed for '{image_path}'. Returning empty list.")
    return []


def format_paddle_results_for_llm(items: List[Dict[str, Any]]) -> str:
    """Format OCR results into an LLM-readable text block."""
    lines = [
        f"{item['text']} | conf={item['confidence']} | pos=({item['center_x']},{item['center_y']})"
        for item in items
    ]
    return "\n".join(lines)
